Remove user ID prompt
RigidStudios/roblox-discord-presence pull request #11
Opened 2022-12-01 10:47 UTC by iUnstable0

its annoying pls xd

2022-12-01 22:08 UTC, RigidStudios requested changes

2022-12-01 22:08 UTC, RigidStudios commented on server/index.js
> +    // }
Just delete the code at this point.

2022-12-01 22:19 UTC, RigidStudios commented
Reason this was included originally was to fulfil setting game activity for when you're outside of studio and playing a game, but I gave up on this project before that ever happened, an implementation of that would be even sweeter but if not I'll merge this once you remove the code.

2022-12-01 23:59 UTC, iUnstable0 commented
oh, i can do it <3, will work on it tomorrow.

2022-12-04 16:49 UTC, iUnstable0 commented
i rewrote the backend if that's fine by you xD (you can revert if u dont like it)
I haven't got time to work on the roblox API presence thingy cuz I was out of town, will work on it tmr :)

2023-01-08 16:49 UTC, Error-Cezar commented
Since Rigid did not push the changes I did it myself.
UserID prompt is now removed.

2023-01-08 16:49 UTC, closed without merging